# Generated by Django 2.2.17 on 2020-11-23 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStats',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hp', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('special_attack', models.IntegerField()),
                ('special_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEvolution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('base_stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokemon.BaseStats')),
                ('evolutions', models.ManyToManyField(to='pokemon.PokemonEvolution')),
            ],
        ),
    ]
